// <auto-generated />
using System;
using KanYonetim.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KanYonetim.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617172258_AddProtocolNumberToDonationRequest")]
    partial class AddProtocolNumberToDonationRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KanYonetim.API.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("KanYonetim.API.Models.BloodStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("HospitalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Units")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BloodTypeId");

                    b.HasIndex("HospitalId", "BloodTypeId")
                        .IsUnique();

                    b.ToTable("BloodStocks");
                });

            modelBuilder.Entity("KanYonetim.API.Models.BloodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BloodTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A+"
                        },
                        new
                        {
                            Id = 2,
                            Name = "A-"
                        },
                        new
                        {
                            Id = 3,
                            Name = "B+"
                        },
                        new
                        {
                            Id = 4,
                            Name = "B-"
                        },
                        new
                        {
                            Id = 5,
                            Name = "AB+"
                        },
                        new
                        {
                            Id = 6,
                            Name = "AB-"
                        },
                        new
                        {
                            Id = 7,
                            Name = "0+"
                        },
                        new
                        {
                            Id = 8,
                            Name = "0-"
                        });
                });

            modelBuilder.Entity("KanYonetim.API.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 40.876100000000001,
                            Longitude = 29.0901,
                            Name = "Adalar"
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 41.184800000000003,
                            Longitude = 28.7394,
                            Name = "Arnavutköy"
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 40.9833,
                            Longitude = 29.116700000000002,
                            Name = "Ataşehir"
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 40.979599999999998,
                            Longitude = 28.721699999999998,
                            Name = "Avcılar"
                        },
                        new
                        {
                            Id = 5,
                            Latitude = 41.039299999999997,
                            Longitude = 28.857199999999999,
                            Name = "Bağcılar"
                        },
                        new
                        {
                            Id = 6,
                            Latitude = 41.002000000000002,
                            Longitude = 28.8614,
                            Name = "Bahçelievler"
                        },
                        new
                        {
                            Id = 7,
                            Latitude = 40.981900000000003,
                            Longitude = 28.876899999999999,
                            Name = "Bakırköy"
                        },
                        new
                        {
                            Id = 8,
                            Latitude = 41.093600000000002,
                            Longitude = 28.7944,
                            Name = "Başakşehir"
                        },
                        new
                        {
                            Id = 9,
                            Latitude = 41.046700000000001,
                            Longitude = 28.902200000000001,
                            Name = "Bayrampaşa"
                        },
                        new
                        {
                            Id = 10,
                            Latitude = 41.042200000000001,
                            Longitude = 29.006699999999999,
                            Name = "Beşiktaş"
                        },
                        new
                        {
                            Id = 11,
                            Latitude = 41.116700000000002,
                            Longitude = 29.100000000000001,
                            Name = "Beykoz"
                        },
                        new
                        {
                            Id = 12,
                            Latitude = 41.005000000000003,
                            Longitude = 28.642800000000001,
                            Name = "Beylikdüzü"
                        },
                        new
                        {
                            Id = 13,
                            Latitude = 41.036900000000003,
                            Longitude = 28.976700000000001,
                            Name = "Beyoğlu"
                        },
                        new
                        {
                            Id = 14,
                            Latitude = 41.020000000000003,
                            Longitude = 28.585599999999999,
                            Name = "Büyükçekmece"
                        },
                        new
                        {
                            Id = 15,
                            Latitude = 41.143300000000004,
                            Longitude = 28.460000000000001,
                            Name = "Çatalca"
                        },
                        new
                        {
                            Id = 16,
                            Latitude = 41.033299999999997,
                            Longitude = 29.183299999999999,
                            Name = "Çekmeköy"
                        },
                        new
                        {
                            Id = 17,
                            Latitude = 41.043599999999998,
                            Longitude = 28.876100000000001,
                            Name = "Esenler"
                        },
                        new
                        {
                            Id = 18,
                            Latitude = 41.033299999999997,
                            Longitude = 28.683299999999999,
                            Name = "Esenyurt"
                        },
                        new
                        {
                            Id = 19,
                            Latitude = 41.0486,
                            Longitude = 28.9344,
                            Name = "Eyüpsultan"
                        },
                        new
                        {
                            Id = 20,
                            Latitude = 41.018599999999999,
                            Longitude = 28.939699999999998,
                            Name = "Fatih"
                        },
                        new
                        {
                            Id = 21,
                            Latitude = 41.066699999999997,
                            Longitude = 28.916699999999999,
                            Name = "Gaziosmanpaşa"
                        },
                        new
                        {
                            Id = 22,
                            Latitude = 41.020299999999999,
                            Longitude = 28.8764,
                            Name = "Güngören"
                        },
                        new
                        {
                            Id = 23,
                            Latitude = 40.992800000000003,
                            Longitude = 29.026399999999999,
                            Name = "Kadıköy"
                        },
                        new
                        {
                            Id = 24,
                            Latitude = 41.078299999999999,
                            Longitude = 28.971399999999999,
                            Name = "Kağıthane"
                        },
                        new
                        {
                            Id = 25,
                            Latitude = 40.906399999999998,
                            Longitude = 29.188600000000001,
                            Name = "Kartal"
                        },
                        new
                        {
                            Id = 26,
                            Latitude = 41.0,
                            Longitude = 28.783300000000001,
                            Name = "Küçükçekmece"
                        },
                        new
                        {
                            Id = 27,
                            Latitude = 40.933300000000003,
                            Longitude = 29.133299999999998,
                            Name = "Maltepe"
                        },
                        new
                        {
                            Id = 28,
                            Latitude = 40.876100000000001,
                            Longitude = 29.2547,
                            Name = "Pendik"
                        },
                        new
                        {
                            Id = 29,
                            Latitude = 41.0,
                            Longitude = 29.2333,
                            Name = "Sancaktepe"
                        },
                        new
                        {
                            Id = 30,
                            Latitude = 41.166699999999999,
                            Longitude = 29.050000000000001,
                            Name = "Sarıyer"
                        },
                        new
                        {
                            Id = 31,
                            Latitude = 41.073599999999999,
                            Longitude = 28.246099999999998,
                            Name = "Silivri"
                        },
                        new
                        {
                            Id = 32,
                            Latitude = 40.959699999999998,
                            Longitude = 29.261700000000001,
                            Name = "Sultanbeyli"
                        },
                        new
                        {
                            Id = 33,
                            Latitude = 41.106699999999996,
                            Longitude = 28.866900000000001,
                            Name = "Sultangazi"
                        },
                        new
                        {
                            Id = 34,
                            Latitude = 41.175600000000003,
                            Longitude = 29.613299999999999,
                            Name = "Şile"
                        },
                        new
                        {
                            Id = 35,
                            Latitude = 41.060000000000002,
                            Longitude = 28.987200000000001,
                            Name = "Şişli"
                        },
                        new
                        {
                            Id = 36,
                            Latitude = 40.816699999999997,
                            Longitude = 29.300000000000001,
                            Name = "Tuzla"
                        },
                        new
                        {
                            Id = 37,
                            Latitude = 41.0167,
                            Longitude = 29.116700000000002,
                            Name = "Ümraniye"
                        },
                        new
                        {
                            Id = 38,
                            Latitude = 41.023600000000002,
                            Longitude = 29.0153,
                            Name = "Üsküdar"
                        },
                        new
                        {
                            Id = 39,
                            Latitude = 41.004199999999997,
                            Longitude = 28.9069,
                            Name = "Zeytinburnu"
                        });
                });

            modelBuilder.Entity("KanYonetim.API.Models.DonationApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DonationRequestId")
                        .HasColumnType("integer");

                    b.Property<int>("DonorId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DonationRequestId");

                    b.HasIndex("DonorId");

                    b.ToTable("DonationApplications");
                });

            modelBuilder.Entity("KanYonetim.API.Models.DonationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HospitalId")
                        .HasColumnType("integer");

                    b.Property<string>("ProtocolNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnitsNeeded")
                        .HasColumnType("integer");

                    b.Property<string>("UrgencyLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BloodTypeId");

                    b.HasIndex("HospitalId");

                    b.ToTable("DonationRequests");
                });

            modelBuilder.Entity("KanYonetim.API.Models.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("UserId");

                    b.ToTable("Hospitals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Çapa, Fatih",
                            DistrictId = 20,
                            Name = "İstanbul Üniversitesi Tıp Fakültesi",
                            Phone = "0212 414 00 00"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Selimiye, Üsküdar",
                            DistrictId = 38,
                            Name = "Haydarpaşa Numune Hastanesi",
                            Phone = "0216 414 45 02"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Halaskargazi Cd., Şişli",
                            DistrictId = 35,
                            Name = "Şişli Hamidiye Etfal Hastanesi",
                            Phone = "0212 373 50 00"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Cevizli, Kartal",
                            DistrictId = 25,
                            Name = "Kartal Dr. Lütfi Kırdar Hastanesi",
                            Phone = "0216 441 39 00"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Zuhuratbaba, Bakırköy",
                            DistrictId = 7,
                            Name = "Bakırköy Dr. Sadi Konuk Hastanesi",
                            Phone = "0212 414 71 71"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Başakşehir",
                            DistrictId = 8,
                            Name = "Başakşehir Çam ve Sakura Hastanesi",
                            Phone = "0212 909 60 00"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Caferağa, Kadıköy",
                            DistrictId = 23,
                            Name = "Kadıköy Devlet Hastanesi",
                            Phone = "0216 346 57 57"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Batı, Pendik",
                            DistrictId = 28,
                            Name = "Pendik Devlet Hastanesi",
                            Phone = "0216 585 05 05"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Kulaksız, Beyoğlu",
                            DistrictId = 13,
                            Name = "Beyoğlu Devlet Hastanesi",
                            Phone = "0212 252 43 00"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Elmalıkent, Ümraniye",
                            DistrictId = 37,
                            Name = "Ümraniye Eğitim Araştırma Hastanesi",
                            Phone = "0216 632 18 18"
                        });
                });

            modelBuilder.Entity("KanYonetim.API.Models.LogisticsTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourierId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DonationRequestId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EstimatedDelivery")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HospitalId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourierId");

                    b.HasIndex("DonationRequestId");

                    b.HasIndex("HospitalId");

                    b.ToTable("LogisticsTransfers");
                });

            modelBuilder.Entity("KanYonetim.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("KanYonetim.API.Models.ProfileActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ProfileActivityLogs");
                });

            modelBuilder.Entity("KanYonetim.API.Models.RequestApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DonationRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("DonationRequestId");

                    b.ToTable("RequestApprovals");
                });

            modelBuilder.Entity("KanYonetim.API.Models.SupportMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<int>("SupportTicketId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("SupportTicketId");

                    b.ToTable("SupportMessages");
                });

            modelBuilder.Entity("KanYonetim.API.Models.SupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("KanYonetim.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowPhoneShare")
                        .HasColumnType("boolean");

                    b.Property<int>("BloodTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailNotifications")
                        .HasColumnType("boolean");

                    b.Property<string>("EmailVerificationCode")
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactPhone")
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactRelation")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasChronicDisease")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastDonationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LocationBasedNotifications")
                        .HasColumnType("boolean");

                    b.Property<string>("NearestHospital")
                        .HasColumnType("text");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfileCompletionRate")
                        .HasColumnType("integer");

                    b.Property<string>("ProfileVisibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RecentAlcoholUse")
                        .HasColumnType("boolean");

                    b.Property<bool>("RecentSurgery")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SmsNotifications")
                        .HasColumnType("boolean");

                    b.Property<string>("Tc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("UsesMedication")
                        .HasColumnType("boolean");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("BloodTypeId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KanYonetim.API.Models.UserActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("UserActivityLogs");
                });

            modelBuilder.Entity("KanYonetim.API.Models.AuditLog", b =>
                {
                    b.HasOne("KanYonetim.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KanYonetim.API.Models.BloodStock", b =>
                {
                    b.HasOne("KanYonetim.API.Models.BloodType", "BloodType")
                        .WithMany("BloodStocks")
                        .HasForeignKey("BloodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanYonetim.API.Models.Hospital", "Hospital")
                        .WithMany("BloodStocks")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodType");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("KanYonetim.API.Models.DonationApplication", b =>
                {
                    b.HasOne("KanYonetim.API.Models.DonationRequest", "DonationRequest")
                        .WithMany("Applications")
                        .HasForeignKey("DonationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanYonetim.API.Models.User", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonationRequest");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("KanYonetim.API.Models.DonationRequest", b =>
                {
                    b.HasOne("KanYonetim.API.Models.BloodType", "BloodType")
                        .WithMany()
                        .HasForeignKey("BloodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanYonetim.API.Models.Hospital", "Hospital")
                        .WithMany("DonationRequests")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodType");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("KanYonetim.API.Models.Hospital", b =>
                {
                    b.HasOne("KanYonetim.API.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanYonetim.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("District");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KanYonetim.API.Models.LogisticsTransfer", b =>
                {
                    b.HasOne("KanYonetim.API.Models.User", "Courier")
                        .WithMany()
                        .HasForeignKey("CourierId");

                    b.HasOne("KanYonetim.API.Models.DonationRequest", "DonationRequest")
                        .WithMany()
                        .HasForeignKey("DonationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanYonetim.API.Models.Hospital", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Courier");

                    b.Navigation("DonationRequest");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("KanYonetim.API.Models.Notification", b =>
                {
                    b.HasOne("KanYonetim.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KanYonetim.API.Models.ProfileActivityLog", b =>
                {
                    b.HasOne("KanYonetim.API.Models.User", "User")
                        .WithMany("ProfileActivityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KanYonetim.API.Models.RequestApproval", b =>
                {
                    b.HasOne("KanYonetim.API.Models.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanYonetim.API.Models.DonationRequest", "DonationRequest")
                        .WithMany()
                        .HasForeignKey("DonationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("DonationRequest");
                });

            modelBuilder.Entity("KanYonetim.API.Models.SupportMessage", b =>
                {
                    b.HasOne("KanYonetim.API.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanYonetim.API.Models.SupportTicket", "SupportTicket")
                        .WithMany("Messages")
                        .HasForeignKey("SupportTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");

                    b.Navigation("SupportTicket");
                });

            modelBuilder.Entity("KanYonetim.API.Models.SupportTicket", b =>
                {
                    b.HasOne("KanYonetim.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KanYonetim.API.Models.User", b =>
                {
                    b.HasOne("KanYonetim.API.Models.BloodType", "BloodType")
                        .WithMany()
                        .HasForeignKey("BloodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanYonetim.API.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodType");

                    b.Navigation("District");
                });

            modelBuilder.Entity("KanYonetim.API.Models.BloodType", b =>
                {
                    b.Navigation("BloodStocks");
                });

            modelBuilder.Entity("KanYonetim.API.Models.DonationRequest", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("KanYonetim.API.Models.Hospital", b =>
                {
                    b.Navigation("BloodStocks");

                    b.Navigation("DonationRequests");
                });

            modelBuilder.Entity("KanYonetim.API.Models.SupportTicket", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("KanYonetim.API.Models.User", b =>
                {
                    b.Navigation("ProfileActivityLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
